Implement `PrintableAsCodeString` for literals
google/summit-ast pull request #20
Opened 2022-08-15 06:13 UTC by eklimo

Implement `PrintableAsCodeString` in `LiteralExpression` to allow clients to get the string value of a literal without knowing its exact type.

For example, there are several places in [PMD](https://github.com/pmd/pmd/blob/master/pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/ast/ASTLiteralExpression.java#L66) where a literal is converted into a string. The concrete type would have to be checked using `instanceof` in each of these situations.

2022-08-15 14:55 UTC, aaronhurst-google requested changes

2022-08-15 14:55 UTC, aaronhurst-google commented on src/main/java/com/google/summit/ast/expression/LiteralExpression.kt
> +    override fun asCodeString(): String = value
The code string for a string literal should be single-quoted.

2022-08-15 15:22 UTC, zorzella approved these changes

2022-08-16 20:04 UTC, aaronhurst-google approved these changes

2022-08-17 21:46 UTC, merged